In [5]:
import pandas as pd
import os
import numpy as np
os.chdir('D://user//User//pydata')
data = pd.read_csv('Fvote.csv', encoding='utf-8')
data.head()

,gender_female,gender_male,region_Chungcheung,region_Honam,region_Others,region_Sudo,region_Youngnam,edu,income,age,score_gov,score_progress,score_intention,vote,parties
0,0,1,0,0,0,0,1,3,3,3,2,2,4.0,1,2
1,0,1,0,0,1,0,0,2,3,3,2,4,3.0,0,3
2,0,1,0,1,0,0,0,1,2,4,1,3,2.8,1,4
3,1,0,0,0,0,1,0,2,1,3,5,4,2.6,1,1
4,0,1,0,0,0,1,0,1,2,4,4,3,2.4,1,1

In [10]:
data.shape

(211, 15)

In [14]:
X=data.iloc[:,0:13]
y=data[['vote']]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, random_state=42)

In [18]:
print(y_train.mean())
print(y_test.mean())

vote    0.708861
dtype: float64
vote    0.716981
dtype: float64

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler_minmax=MinMaxScaler()

In [44]:
scaler_minmax.fit(X_train)
X_scaled_minmax_train=scaler_minmax.transform(X_train)

In [25]:
pd.DataFrame(X_scaled_minmax_train).describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,0.322785,0.677215,0.094937,0.056962,0.101266,0.601266,0.145570,0.436709,0.392405,0.554852,0.507911,0.518987,0.477532
std,0.469028,0.469028,0.294060,0.232507,0.302640,0.491195,0.353796,0.312857,0.355960,0.295306,0.235099,0.245248,0.187215
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.312500,0.250000,0.350000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.500000,0.333333,0.500000,0.500000,0.500000,0.500000
75%,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.500000,0.666667,0.666667,0.750000,0.750000,0.600000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [46]:
X_scaled_minmax_test = scaler_minmax.transform(X_test)
pd.DataFrame(X_scaled_minmax_test).describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,0.396226,0.603774,0.037736,0.188679,0.075472,0.584906,0.113208,0.424528,0.433962,0.540881,0.533019,0.537736,0.478302
std,0.493793,0.493793,0.192380,0.394998,0.266679,0.497454,0.319878,0.316170,0.355572,0.279089,0.240381,0.226789,0.163939
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.500000,0.500000,0.350000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.500000,0.333333,0.666667,0.500000,0.500000,0.500000
75%,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.500000,0.666667,0.666667,0.750000,0.750000,0.550000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.900000

## Standardizaition 스케일링

In [28]:
#표준화란 평균이 0, 표준편차가 1이 되도록 특성치의 단위를 정규화 하는것\
from sklearn.preprocessing import StandardScaler
scaler_standard=StandardScaler()

In [29]:
scaler_standard.fit(X_train)
X_scaler_standard_train=scaler_standard.transform(X_train)

In [31]:
pd.DataFrame(X_scaler_standard_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.448461,-1.448461,-0.323875,-0.24577,-0.335673,-1.227981,2.422719,0.202944,1.712345,-0.752519,-0.033758,-0.077667,-0.683372
1,-0.690388,0.690388,3.087610,-0.24577,-0.335673,-1.227981,-0.412759,-1.400312,-0.166478,1.512205,-1.100523,-1.100283,-1.219217
2,-0.690388,0.690388,-0.323875,-0.24577,-0.335673,0.814345,-0.412759,-1.400312,-0.166478,0.379843,-1.100523,0.944949,-0.951294
3,-0.690388,0.690388,-0.323875,-0.24577,-0.335673,-1.227981,2.422719,1.806199,1.712345,0.379843,-2.167287,-1.100283,-1.219217
4,-0.690388,0.690388,-0.323875,-0.24577,-0.335673,0.814345,-0.412759,1.806199,1.712345,0.379843,2.099770,-1.100283,-2.558829
...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,-0.690388,0.690388,-0.323875,-0.24577,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-0.752519,-1.100523,-1.100283,-0.683372
154,1.448461,-1.448461,-0.323875,-0.24577,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-0.752519,-1.100523,0.944949,0.120396
155,-0.690388,0.690388,-0.323875,-0.24577,2.979094,-1.227981,-0.412759,0.202944,1.712345,1.512205,-0.033758,0.944949,0.924163
156,-0.690388,0.690388,-0.323875,-0.24577,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-0.752519,1.033006,0.944949,1.192085
157,1.448461,-1.448461,-0.323875,-0.24577,-0.335673,0.814345,-0.412759,0.202944,-1.105890,-0.752519,1.033006,0.944949,0.120396

In [36]:
X_scaler_standard_test=scaler_standard.transform(X_test)
pd.DataFrame(X_scaler_standard_test)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-0.690388,0.690388,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,0.202944,-0.166478,-0.752519,-0.033758,-0.077667,-0.951294
1,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,0.772934,0.379843,-1.100523,-1.100283,-0.683372
2,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,0.772934,-0.752519,-0.033758,0.944949,-1.487139
3,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-0.166478,1.512205,-2.167287,-2.122900,-0.415449
4,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,-1.227981,2.422719,-1.400312,-1.105890,0.379843,-0.033758,-1.100283,-0.415449
5,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,-1.227981,2.422719,0.202944,-1.105890,-0.752519,-0.033758,-0.077667,0.388318
6,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,1.806199,-1.105890,-0.752519,1.033006,0.944949,1.192085
7,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-1.884881,-0.033758,0.944949,-0.147527
8,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-0.166478,-0.752519,-0.033758,-0.077667,0.120396
9,-0.690388,0.690388,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,-1.400312,-0.166478,1.512205,-2.167287,-0.077667,-0.147527
10,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,0.772934,1.512205,-1.100523,-1.100283,0.120396
11,-0.690388,0.690388,-0.323875,-0.245770,2.979094,-1.227981,-0.412759,0.202944,1.712345,0.379843,1.033006,-0.077667,1.460008
12,-0.690388,0.690388,-0.323875,-0.245770,2.979094,-1.227981,-0.412759,1.806199,1.712345,0.379843,-0.033758,-0.077667,0.388318
13,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-0.166478,0.379843,-1.100523,-1.100283,-1.219217
14,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-0.166478,0.379843,1.033006,-1.100283,0.120396
15,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,-1.227981,2.422719,1.806199,-0.166478,-0.752519,-1.100523,-0.077667,0.120396
16,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-0.752519,-0.033758,-0.077667,1.995853
17,1.448461,-1.448461,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,0.202944,-0.166478,-0.752519,-0.033758,-0.077667,-1.219217
18,-0.690388,0.690388,-0.323875,-0.245770,2.979094,-1.227981,-0.412759,0.202944,-0.166478,-0.752519,-0.033758,-1.100283,-1.219217
19,-0.690388,0.690388,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,0.202944,1.712345,0.379843,-0.033758,-1.100283,0.120396
20,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,1.712345,1.512205,-0.033758,-0.077667,-1.219217
21,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-0.166478,-0.752519,-0.033758,1.967565,1.460008
22,-0.690388,0.690388,3.087610,-0.245770,-0.335673,-1.227981,-0.412759,0.202944,1.712345,0.379843,-0.033758,-0.077667,0.388318
23,1.448461,-1.448461,-0.323875,-0.245770,2.979094,-1.227981,-0.412759,1.806199,0.772934,1.512205,-0.033758,0.944949,0.656241
24,-0.690388,0.690388,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,-1.400312,0.772934,0.379843,1.033006,0.944949,-0.683372
25,-0.690388,0.690388,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,0.202944,1.712345,1.512205,-0.033758,-0.077667,0.924163
26,1.448461,-1.448461,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,0.202944,1.712345,0.379843,-1.100523,-1.100283,-1.487139
27,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,-1.227981,2.422719,0.202944,-0.166478,0.379843,1.033006,1.967565,0.656241
28,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-1.105890,-0.752519,1.033006,-0.077667,0.120396
29,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-1.105890,-0.752519,1.033006,0.944949,-0.951294
30,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,-1.227981,2.422719,0.202944,-0.166478,1.512205,1.033006,-1.100283,-0.415449
31,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-0.166478,1.512205,1.033006,-0.077667,-0.683372
32,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,0.772934,-0.752519,-1.100523,-0.077667,0.388318
33,-0.690388,0.690388,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,0.202944,0.772934,0.379843,1.033006,0.944949,0.120396
34,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-0.166478,0.379843,2.099770,0.944949,-0.415449
35,-0.690388,0.690388,3.087610,-0.245770,-0.335673,-1.227981,-0.412759,1.806199,0.772934,1.512205,-1.100523,0.944949,0.388318
36,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,1.806199,0.772934,0.379843,1.033006,0.944949,0.388318
37,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-1.105890,-0.752519,1.033006,0.944949,-0.951294
38,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,0.772934,0.379843,-2.167287,-1.100283,0.120396
39,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-0.752519,-1.100523,-1.100283,-0.147527
40,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-0.166478,-0.752519,-0.033758,0.944949,0.924163
41,-0.690388,0.690388,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,0.202944,0.772934,-0.752519,2.099770,0.944949,0.388318
42,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-0.166478,-0.752519,1.033006,-0.077667,-0.951294
43,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-1.105890,-0.752519,-0.033758,-0.077667,0.656241
44,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,0.772934,0.379843,1.033006,0.944949,0.120396
45,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-1.105890,-0.752519,-0.033758,-0.077667,-0.415449
46,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,-1.227981,2.422719,1.806199,0.772934,0.379843,-1.100523,-1.100283,1.460008
47,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-0.752519,-0.033758,-0.077667,0.120396
48,1.448461,-1.448461,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,-1.400312,-1.105890,-1.884881,2.099770,0.944949,0.388318
49,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,-1.105890,-0.752519,-0.033758,0.944949,-0.415449
50,1.448461,-1.448461,-0.323875,4.068852,-0.335673,-1.227981,-0.412759,-1.400312,-1.105890,-1.884881,-0.033758,-0.077667,0.388318
51,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,1.712345,-0.752519,1.033006,-0.077667,2.263775
52,-0.690388,0.690388,-0.323875,-0.245770,-0.335673,0.814345,-0.412759,0.202944,1.712345,0.379843,1.033006,1.967565,-1.487139

## 모델학습

In [39]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_scaled_minmax_train, y_train)

D:\user\User\CEO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

LogisticRegression()

In [40]:
pred_train = model.predict(X_scaled_minmax_train)

In [41]:
model.score(X_scaled_minmax_train,y_train)

0.7278481012658228

In [50]:
pred_test = model.predict(X_scaled_minmax_test)
model.score(X_scaled_minmax_test,y_test)

0.7169811320754716

In [53]:
## 혼동행렬
from sklearn.metrics import confusion_matrix

In [57]:
confusion_train = confusion_matrix(y_train, pred_train)
print("훈련데이터 오차행렬: \n", confusion_train)

훈련데이터 오차행렬:
 [[  9  37]
 [  6 106]]

In [58]:
confusion_test = confusion_matrix(y_test, pred_test)
print('테스트데이터 오차행렬: \n', confusion_train)

테스트데이터 오차행렬:
 [[  9  37]
 [  6 106]]

## Standardize 데이터 적용결과

In [62]:
model.fit(X_scaler_standard_train, y_train)

D:\user\User\CEO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

LogisticRegression()

In [63]:
model.score(X_scaler_standard_train,y_train)

0.740506329113924

In [65]:
pred_train = model.predict(X_scaler_standard_train)

In [66]:
pred_test = model.predict(X_scaler_standard_test)

In [68]:
model.score(X_scaler_standard_test,y_test )

0.6792452830188679

In [72]:
confusion_test = confusion_matrix(y_test, pred_test)

In [73]:
print('테스트데이터 오차행렬 : \n', confusion_test)

테스트데이터 오차행렬 :
 [[ 3 12]
 [ 5 33]]